on: 
  push:
    branches:
    - master

jobs:
  Lint:
    name: Lint test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Eslint
      uses: docker://pojome/php-js-lints
      with:
        entrypoint: /bin/bash eslint .
